name: Android Deploy

on:
  push:
    branches:
      - staging

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout to git repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile --network-timeout 300000

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Clean build
        run: |
          cd android
          ./gradlew clean
          cd ..

      - name: Show RAM
        run: free -h && lscpu

      - name: Build
        run: |
          cd android
          ./gradlew build
          cd ..

      - name: Assemble Release Bundle
        run: |
          cd android
          ./gradlew bundleRelease
          cd ..

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.APP_INSTALADOR_STORE_FILE }}
          alias: ${{ secrets.APP_INSTALADOR_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.APP_INSTALADOR_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.APP_INSTALADOR_KEY_PASSWORD }}

      - name: Bump version
        run: |
          chmod +x android/increment-version.sh
          ./android/increment-version.sh

      - name: Create service_account.json
        run: echo '${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}' > service_account.json

      - name: Deploy to Alpha
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.fastlane
          releaseFile: android/app/build/outputs/bundle/release/app-release.aab
          track: internal
          whatsNewDirectory: distribution/

      - name: Commit and push version change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: Atualizado versionCode e versionName'
          file_pattern: 'android/app/build.gradle'
