name: build-ios
on:
  push:
    branches:
      - 'ios'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout to git repository
        uses: actions/checkout@v4

      - name: Install gem fastlane
        run: |
          gem install fastlane

      - name: Install ruby
        run: |
          brew install ruby

      - name: Check version ruby
        run: |
          ruby --version

      - name: Default scheme
        run: |
          name: Set Default Scheme

      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty && exit ${PIPESTATUS[0]}

      - name: Ios version
        run: |
          fastlane beta


      