name: Create Tag and Release

on:
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get package version
        id: get_package_version
        run: |
          version=$(jq -r '.version' package.json)
          echo "::set-output name=version::$version"

      - uses: rickstaa/action-create-tag@v1
        id: 'tag_create'
        with:
          tag: v${{ steps.get_package_version.outputs.version }}
          tag_exists_error: false
          message: 'Latest release'

      - name: Extract changelog for release version
        run: |
          chmod +x extract-changelog.sh
          ./extract-changelog.sh

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: v${{ steps.get_package_version.outputs.version }}
          release_name: v${{ steps.get_package_version.outputs.version }}
          body_path: RELEASE.md
          draft: false
          prerelease: false
