name: Create/update tag

on:
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get package version
        id: get_package_version
        run: |
          version=$(jq -r '.version' package.json)
          echo "::set-output name=version::$version"

      - uses: rickstaa/action-create-tag@v1
        id: 'tag_create'
        with:
          tag: v${{ steps.get_package_version.outputs.version }}
          tag_exists_error: false
          message: 'Latest release'

      # Print result using the env variable.
      - run: |
        echo "Tag already present: ${{ env.TAG_EXISTS }}"

      # Print result using the action output.
      - run: |
        echo "Tag already present: ${{ steps.tag_create.outputs.tag_exists }}"
