name: Pump

on:
  push:
    branches:
      - staging

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout to git repository
        uses: actions/checkout@v4

      - name: Bump version
        run: |
          chmod +x android/increment-version.sh
          ./android/increment-version.sh

      - name: Show build.gradle
        run: |
          cat android/app/build.gradle | grep versionCode
          cat android/app/build.gradle | grep versionName

      - name: Commit and push version change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: Atualizado versionCode e versionName'
          file_pattern: 'android/app/build.gradle'
